export const blockedWords: string[] = [
	// Music-related terms
	"lyrics",
	"lyric",
	"+LYRICS",
	"audio",
	"music",
	"musicvideo",
	"music-video",
	"music video",
	"vevo",
	"original mix",
	"mix",
	"bass boosted",
	"boosted",
	"bass",
	"acoustic",
	"EP",
	"karaoke",
	"lofi",
	"lo-fi",
	"lo fi",
	"lofibeats",
	"lo-fi hip hop",

	// Video-related terms
	"video",
	"official-musicvideo",
	"official-audio",
	"official",
	"official mv",
	"official-mv",
	"official visualizer",
	"official-visualizer",
	"visualizer",
	"official video",
	"lyric video",
	"animated",
	"m/v",
	"MV",
	"Official HD Music Video",

	// Live and performance-related terms
	"live",
	"live performance",
	"vod",

	// Duration-related terms
	"1 hour",
	"2 hour",
	"3 hour",
	"4 hour",
	"5 hour",
	"6 hour",
	"7 hour",
	"8 hour",
	"9 hour",
	"10 hour",
	"11 hour",
	"12 hour",
	"13 hour",
	"15 hour",
	"16 hour",
	"17 hour",
	"18 hour",
	"19 hour",
	"20 hour",
	"21 hour",
	"23 hour",
	"24 hour",
	"48 hour",
	"full version",

	// Music labels and channels
	"free music",
	"ncs release",
	"- Topic - ",
	"GRM Daily",
	"Monstercat Release",
	"trapnation",
	"trapcity",
	"proximity",
	"majesticcasual",
	"suicide sheep",
	"mrrevillz",
	"taz network",
	"cloudkid",
	"xkito",
	"dynmk",
	"mrsuicidesheep",
	"chill nation",
	"indie nation",
	"thegrimeviolinist",
	"liquicity",
	"epic network",
	"pandora journey",
	"edm.com",
	"house nation",
	"monstercat",
	"nocopyrightsounds",
	"ncs",
	"nghbrs",
	"chillhop music",
	"chilledcow",

	// Social media and engagement terms
	"Tik Tok",
	"TikTok",
	"FREE DOWNLOAD",
	"stream",
	"download",
	"subscribe",
	"comment",
	"like",
	"share",
	"follow",

	// Mood and genre-related terms
	"ambient music",
	"relaxing music",
	"study music",
	"focus music",
	"calming music",
	"sleep music",
	"reverb",

	// Symbols and formatting characters
	"♪",
	"|",
	"~",
	"『",
	"』",

	// Non-English terms
	"clip officiel",
	"Audio oficial",
	"Áudio oficial",
	"Offizielles Audio",
	"Audio resmi",
	"Audio officiel",
	"Resmi ses dosyası",
	"Videoclipe Oficial",
	"Clipe Oficial",
	"video officiale",
	"offizielles video",
	// Additional non-English terms
	"Vídeo oficial",
	"Видео официальное",
	"Offizielle Musik",
	"Musique officielle",
	"Música oficial",
	"Ufficiale musica",
	"公式ミュージックビデオ",
	"官方音乐视频",
	"공식 뮤직비디오",
	"Vídeo musical oficial",
	"Videoclip ufficiale",
	"Clip de musique officiel",
	"Offizielles Musikvideo",
	"Официальный клип",
	"Resmi müzik videosu",
	"Oficjalne wideo",
	"Officiële videoclip",
	"Επίσημο βίντεο κλιπ",
	"Resmi video klip",
	"Offisiell musikkvideo",
	"Officiell musikvideo",
	"Virallinen musiikkivideo",
	"Oficialus muzikinis vaizdo klipas",
	"Zyrtare video muzikore",
	"Rasmi muzik video",
	"Chính thức video âm nhạc",
	"Resmi müzik klibi",
	"Oficjalne audio",
	"Officiële audio",
	"Аудио официальное",
	"音声公式",
	"官方音频",
	"공식 오디오",

	// Additional terms
	"remix",
	"cover",
	"instrumental",
	"extended mix",
	"radio edit",
	"feat.",
	"ft.",
	"featuring",
	"prod. by",
	"produced by",
	"official lyric video",
	"official audio",
	"official music video",
	"behind the scenes",
	"making of",
	"teaser",
	"trailer",
	"preview",
	"snippet",
	"exclusive",
	"premiere",
	"remastered",
	"remaster",
	"high quality",
	"HQ",
	"HD",
	"4K",
	"8K",
	"surround sound",
	"dolby atmos",
];